import { SYSTEM_PROMPT_SINGLE, SYSTEM_PROMPT_MIX, MODEL_NAME } from "../constants";
import { fileToBase64 } from "../utils/imageUtils";
import { GenerationMode } from "../types";

/**
 * Generate image securely via Cloudflare Pages Function
 * API key is hidden in Cloudflare (GEMINI_API_KEY secret)
 */
export const generateImageFromReferences = async (
  imageFiles: File[],
  mode: GenerationMode
): Promise<string> => {

  try {

    // 🧠 Select hidden system prompt
    const systemPrompt =
      mode === "single"
        ? SYSTEM_PROMPT_SINGLE
        : SYSTEM_PROMPT_MIX;


    // 🖼 Convert images to base64
    const imageParts = await Promise.all(

      imageFiles.map(async (file) => ({

        inlineData: {

          mimeType: file.type,

          data: await fileToBase64(file),

        },

      }))

    );


    // 🧩 Combine images + prompt
    const contents = {

      parts: [

        ...imageParts,

        {

          text: systemPrompt,

        },

      ],

    };


    // 🎯 Dynamic aspect ratio
    const aspectRatio =
      mode === "single"
        ? "1:1"   // single image → square
        : "9:16"; // multiple images → vertical


    // 🎯 Dynamic quality
    const imageSize =
      mode === "single"
        ? "1K"  // higher quality for product
        : "1K"; // faster for mix



    // 🌐 Call Cloudflare Pages Function
    const response = await fetch("/api/generate", {

      method: "POST",

      headers: {

        "Content-Type": "application/json",

      },

      body: JSON.stringify({

        model: MODEL_NAME,

        contents: contents,

        config: {

          imageConfig: {

            aspectRatio: aspectRatio,

            imageSize: imageSize,

          },

        },

      }),

    });



    // ❌ Handle server errors
    if (!response.ok) {

      const errorText = await response.text();

      throw new Error(`Server error: ${errorText}`);

    }



    const result = await response.json();



    // 🖼 Extract generated image
    let generatedImageUrl: string | null = null;



    if (result.candidates?.length > 0) {

      const parts = result.candidates[0]?.content?.parts;

      if (parts) {

        for (const part of parts) {

          if (part.inlineData?.data) {

            generatedImageUrl =
              `data:image/png;base64,${part.inlineData.data}`;

            break;

          }

        }

      }

    }



    if (!generatedImageUrl)

      throw new Error("No image generated by API");



    return generatedImageUrl;



  }

  catch (error) {

    console.error("Image generation failed:", error);

    throw error;

  }

};
